// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tokens.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createToken = `-- name: CreateToken :one
INSERT INTO tokens (user_id, token, type, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, token, type, expires_at, used_at, created_at
`

type CreateTokenParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	Token     string             `json:"token"`
	Type      TokenType          `json:"type"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) (Token, error) {
	row := q.db.QueryRow(ctx, createToken,
		arg.UserID,
		arg.Token,
		arg.Type,
		arg.ExpiresAt,
	)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.Type,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredTokens = `-- name: DeleteExpiredTokens :exec
DELETE FROM tokens WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredTokens)
	return err
}

const deleteTokensByUserAndType = `-- name: DeleteTokensByUserAndType :exec
DELETE FROM tokens WHERE user_id = $1 AND type = $2
`

type DeleteTokensByUserAndTypeParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Type   TokenType   `json:"type"`
}

func (q *Queries) DeleteTokensByUserAndType(ctx context.Context, arg DeleteTokensByUserAndTypeParams) error {
	_, err := q.db.Exec(ctx, deleteTokensByUserAndType, arg.UserID, arg.Type)
	return err
}

const getTokenByHash = `-- name: GetTokenByHash :one
SELECT id, user_id, token, type, expires_at, used_at, created_at FROM tokens
WHERE token = $1 AND type = $2
LIMIT 1
`

type GetTokenByHashParams struct {
	Token string    `json:"token"`
	Type  TokenType `json:"type"`
}

func (q *Queries) GetTokenByHash(ctx context.Context, arg GetTokenByHashParams) (Token, error) {
	row := q.db.QueryRow(ctx, getTokenByHash, arg.Token, arg.Type)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.Type,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listRecoveryTokensByUser = `-- name: ListRecoveryTokensByUser :many
SELECT id, user_id, token, type, expires_at, used_at, created_at FROM tokens
WHERE user_id = $1 AND type = 'totp_recovery' AND used_at IS NULL
ORDER BY created_at ASC
`

func (q *Queries) ListRecoveryTokensByUser(ctx context.Context, userID pgtype.UUID) ([]Token, error) {
	rows, err := q.db.Query(ctx, listRecoveryTokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Token{}
	for rows.Next() {
		var i Token
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Token,
			&i.Type,
			&i.ExpiresAt,
			&i.UsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTokenUsed = `-- name: MarkTokenUsed :one
UPDATE tokens
SET used_at = NOW()
WHERE id = $1
RETURNING id, user_id, token, type, expires_at, used_at, created_at
`

func (q *Queries) MarkTokenUsed(ctx context.Context, id pgtype.UUID) (Token, error) {
	row := q.db.QueryRow(ctx, markTokenUsed, id)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.Type,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}
