// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelSoftDelete = `-- name: CancelSoftDelete :one
UPDATE users
SET deleted_at = NULL,
    status     = 'active',
    updated_at = NOW()
WHERE id = $1
RETURNING id, email, hashed_password, first_name, last_name, display_name, bio, avatar_url, role, status, is_email_verified, totp_secret, is_2fa_enabled, last_login_at, deleted_at, created_at, updated_at
`

func (q *Queries) CancelSoftDelete(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, cancelSoftDelete, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.FirstName,
		&i.LastName,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.Role,
		&i.Status,
		&i.IsEmailVerified,
		&i.TotpSecret,
		&i.Is2faEnabled,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
WHERE deleted_at IS NULL
  AND ($1 = '' OR role::text = $1)
  AND ($2 = '' OR status::text = $2)
  AND ($3 = '' OR is_email_verified = ($3 = 'true'))
  AND ($4 = '' OR email ILIKE '%' || $4 || '%' OR display_name ILIKE '%' || $4 || '%')
`

type CountUsersParams struct {
	Column1 interface{} `json:"column_1"`
	Column2 interface{} `json:"column_2"`
	Column3 interface{} `json:"column_3"`
	Column4 interface{} `json:"column_4"`
}

func (q *Queries) CountUsers(ctx context.Context, arg CountUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, hashed_password, first_name, last_name, display_name, role)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, email, hashed_password, first_name, last_name, display_name, bio, avatar_url, role, status, is_email_verified, totp_secret, is_2fa_enabled, last_login_at, deleted_at, created_at, updated_at
`

type CreateUserParams struct {
	Email          string   `json:"email"`
	HashedPassword string   `json:"hashed_password"`
	FirstName      string   `json:"first_name"`
	LastName       string   `json:"last_name"`
	DisplayName    string   `json:"display_name"`
	Role           UserRole `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.HashedPassword,
		arg.FirstName,
		arg.LastName,
		arg.DisplayName,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.FirstName,
		&i.LastName,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.Role,
		&i.Status,
		&i.IsEmailVerified,
		&i.TotpSecret,
		&i.Is2faEnabled,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const disable2FA = `-- name: Disable2FA :one
UPDATE users
SET totp_secret    = NULL,
    is_2fa_enabled = FALSE,
    updated_at     = NOW()
WHERE id = $1
RETURNING id, email, hashed_password, first_name, last_name, display_name, bio, avatar_url, role, status, is_email_verified, totp_secret, is_2fa_enabled, last_login_at, deleted_at, created_at, updated_at
`

func (q *Queries) Disable2FA(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, disable2FA, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.FirstName,
		&i.LastName,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.Role,
		&i.Status,
		&i.IsEmailVerified,
		&i.TotpSecret,
		&i.Is2faEnabled,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const enable2FA = `-- name: Enable2FA :one
UPDATE users
SET totp_secret    = $2,
    is_2fa_enabled = $3,
    updated_at     = NOW()
WHERE id = $1
RETURNING id, email, hashed_password, first_name, last_name, display_name, bio, avatar_url, role, status, is_email_verified, totp_secret, is_2fa_enabled, last_login_at, deleted_at, created_at, updated_at
`

type Enable2FAParams struct {
	ID           pgtype.UUID `json:"id"`
	TotpSecret   pgtype.Text `json:"totp_secret"`
	Is2faEnabled bool        `json:"is_2fa_enabled"`
}

func (q *Queries) Enable2FA(ctx context.Context, arg Enable2FAParams) (User, error) {
	row := q.db.QueryRow(ctx, enable2FA, arg.ID, arg.TotpSecret, arg.Is2faEnabled)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.FirstName,
		&i.LastName,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.Role,
		&i.Status,
		&i.IsEmailVerified,
		&i.TotpSecret,
		&i.Is2faEnabled,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, hashed_password, first_name, last_name, display_name, bio, avatar_url, role, status, is_email_verified, totp_secret, is_2fa_enabled, last_login_at, deleted_at, created_at, updated_at FROM users WHERE email = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.FirstName,
		&i.LastName,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.Role,
		&i.Status,
		&i.IsEmailVerified,
		&i.TotpSecret,
		&i.Is2faEnabled,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, hashed_password, first_name, last_name, display_name, bio, avatar_url, role, status, is_email_verified, totp_secret, is_2fa_enabled, last_login_at, deleted_at, created_at, updated_at FROM users WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.FirstName,
		&i.LastName,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.Role,
		&i.Status,
		&i.IsEmailVerified,
		&i.TotpSecret,
		&i.Is2faEnabled,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hardDeleteUser = `-- name: HardDeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) HardDeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, hardDeleteUser, id)
	return err
}

const listActiveUsers = `-- name: ListActiveUsers :many
SELECT id, email, hashed_password, first_name, last_name, display_name, bio, avatar_url, role, status, is_email_verified, totp_secret, is_2fa_enabled, last_login_at, deleted_at, created_at, updated_at FROM users
WHERE status = 'active' AND deleted_at IS NULL
`

func (q *Queries) ListActiveUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listActiveUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.HashedPassword,
			&i.FirstName,
			&i.LastName,
			&i.DisplayName,
			&i.Bio,
			&i.AvatarUrl,
			&i.Role,
			&i.Status,
			&i.IsEmailVerified,
			&i.TotpSecret,
			&i.Is2faEnabled,
			&i.LastLoginAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, hashed_password, first_name, last_name, display_name, bio, avatar_url, role, status, is_email_verified, totp_secret, is_2fa_enabled, last_login_at, deleted_at, created_at, updated_at FROM users
WHERE deleted_at IS NULL
  AND ($1 = '' OR role::text = $1)
  AND ($2 = '' OR status::text = $2)
  AND ($3 = '' OR is_email_verified = ($3 = 'true'))
  AND ($4 = '' OR email ILIKE '%' || $4 || '%' OR display_name ILIKE '%' || $4 || '%')
ORDER BY created_at DESC
LIMIT $5 OFFSET $6
`

type ListUsersParams struct {
	Column1 interface{} `json:"column_1"`
	Column2 interface{} `json:"column_2"`
	Column3 interface{} `json:"column_3"`
	Column4 interface{} `json:"column_4"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

// $3: ” = all, 'true' = verified only, 'false' = unverified only
func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.HashedPassword,
			&i.FirstName,
			&i.LastName,
			&i.DisplayName,
			&i.Bio,
			&i.AvatarUrl,
			&i.Role,
			&i.Status,
			&i.IsEmailVerified,
			&i.TotpSecret,
			&i.Is2faEnabled,
			&i.LastLoginAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersScheduledForHardDelete = `-- name: ListUsersScheduledForHardDelete :many
SELECT id, email, hashed_password, first_name, last_name, display_name, bio, avatar_url, role, status, is_email_verified, totp_secret, is_2fa_enabled, last_login_at, deleted_at, created_at, updated_at FROM users
WHERE deleted_at IS NOT NULL
  AND deleted_at < NOW() - INTERVAL '30 days'
`

func (q *Queries) ListUsersScheduledForHardDelete(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersScheduledForHardDelete)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.HashedPassword,
			&i.FirstName,
			&i.LastName,
			&i.DisplayName,
			&i.Bio,
			&i.AvatarUrl,
			&i.Role,
			&i.Status,
			&i.IsEmailVerified,
			&i.TotpSecret,
			&i.Is2faEnabled,
			&i.LastLoginAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setEmailVerified = `-- name: SetEmailVerified :one
UPDATE users
SET is_email_verified = TRUE,
    status            = 'active',
    updated_at        = NOW()
WHERE id = $1
RETURNING id, email, hashed_password, first_name, last_name, display_name, bio, avatar_url, role, status, is_email_verified, totp_secret, is_2fa_enabled, last_login_at, deleted_at, created_at, updated_at
`

func (q *Queries) SetEmailVerified(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, setEmailVerified, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.FirstName,
		&i.LastName,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.Role,
		&i.Status,
		&i.IsEmailVerified,
		&i.TotpSecret,
		&i.Is2faEnabled,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const softDeleteUser = `-- name: SoftDeleteUser :one
UPDATE users
SET deleted_at = NOW(),
    status     = 'inactive',
    updated_at = NOW()
WHERE id = $1
RETURNING id, email, hashed_password, first_name, last_name, display_name, bio, avatar_url, role, status, is_email_verified, totp_secret, is_2fa_enabled, last_login_at, deleted_at, created_at, updated_at
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, softDeleteUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.FirstName,
		&i.LastName,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.Role,
		&i.Status,
		&i.IsEmailVerified,
		&i.TotpSecret,
		&i.Is2faEnabled,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLastLogin = `-- name: UpdateLastLogin :one
UPDATE users
SET last_login_at = NOW(),
    updated_at    = NOW()
WHERE id = $1
RETURNING id, email, hashed_password, first_name, last_name, display_name, bio, avatar_url, role, status, is_email_verified, totp_secret, is_2fa_enabled, last_login_at, deleted_at, created_at, updated_at
`

func (q *Queries) UpdateLastLogin(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, updateLastLogin, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.FirstName,
		&i.LastName,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.Role,
		&i.Status,
		&i.IsEmailVerified,
		&i.TotpSecret,
		&i.Is2faEnabled,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserAvatarURL = `-- name: UpdateUserAvatarURL :one
UPDATE users
SET avatar_url = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, email, hashed_password, first_name, last_name, display_name, bio, avatar_url, role, status, is_email_verified, totp_secret, is_2fa_enabled, last_login_at, deleted_at, created_at, updated_at
`

type UpdateUserAvatarURLParams struct {
	ID        pgtype.UUID `json:"id"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
}

func (q *Queries) UpdateUserAvatarURL(ctx context.Context, arg UpdateUserAvatarURLParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserAvatarURL, arg.ID, arg.AvatarUrl)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.FirstName,
		&i.LastName,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.Role,
		&i.Status,
		&i.IsEmailVerified,
		&i.TotpSecret,
		&i.Is2faEnabled,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserEmail = `-- name: UpdateUserEmail :one
UPDATE users
SET email      = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, email, hashed_password, first_name, last_name, display_name, bio, avatar_url, role, status, is_email_verified, totp_secret, is_2fa_enabled, last_login_at, deleted_at, created_at, updated_at
`

type UpdateUserEmailParams struct {
	ID    pgtype.UUID `json:"id"`
	Email string      `json:"email"`
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserEmail, arg.ID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.FirstName,
		&i.LastName,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.Role,
		&i.Status,
		&i.IsEmailVerified,
		&i.TotpSecret,
		&i.Is2faEnabled,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users
SET hashed_password = $2,
    updated_at      = NOW()
WHERE id = $1
RETURNING id, email, hashed_password, first_name, last_name, display_name, bio, avatar_url, role, status, is_email_verified, totp_secret, is_2fa_enabled, last_login_at, deleted_at, created_at, updated_at
`

type UpdateUserPasswordParams struct {
	ID             pgtype.UUID `json:"id"`
	HashedPassword string      `json:"hashed_password"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPassword, arg.ID, arg.HashedPassword)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.FirstName,
		&i.LastName,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.Role,
		&i.Status,
		&i.IsEmailVerified,
		&i.TotpSecret,
		&i.Is2faEnabled,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET first_name   = $2,
    last_name    = $3,
    display_name = $4,
    bio          = $5,
    updated_at   = NOW()
WHERE id = $1
RETURNING id, email, hashed_password, first_name, last_name, display_name, bio, avatar_url, role, status, is_email_verified, totp_secret, is_2fa_enabled, last_login_at, deleted_at, created_at, updated_at
`

type UpdateUserProfileParams struct {
	ID          pgtype.UUID `json:"id"`
	FirstName   string      `json:"first_name"`
	LastName    string      `json:"last_name"`
	DisplayName string      `json:"display_name"`
	Bio         pgtype.Text `json:"bio"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.DisplayName,
		arg.Bio,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.FirstName,
		&i.LastName,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.Role,
		&i.Status,
		&i.IsEmailVerified,
		&i.TotpSecret,
		&i.Is2faEnabled,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE users
SET role       = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, email, hashed_password, first_name, last_name, display_name, bio, avatar_url, role, status, is_email_verified, totp_secret, is_2fa_enabled, last_login_at, deleted_at, created_at, updated_at
`

type UpdateUserRoleParams struct {
	ID   pgtype.UUID `json:"id"`
	Role UserRole    `json:"role"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserRole, arg.ID, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.FirstName,
		&i.LastName,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.Role,
		&i.Status,
		&i.IsEmailVerified,
		&i.TotpSecret,
		&i.Is2faEnabled,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserStatus = `-- name: UpdateUserStatus :one
UPDATE users
SET status     = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, email, hashed_password, first_name, last_name, display_name, bio, avatar_url, role, status, is_email_verified, totp_secret, is_2fa_enabled, last_login_at, deleted_at, created_at, updated_at
`

type UpdateUserStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status UserStatus  `json:"status"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserStatus, arg.ID, arg.Status)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.FirstName,
		&i.LastName,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.Role,
		&i.Status,
		&i.IsEmailVerified,
		&i.TotpSecret,
		&i.Is2faEnabled,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
